version: '3'
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment: 
      - discovery.type=single-node
    volumes: 
      - data:/usr/share/elasticsearch/data
    ports: 
      - "9200:9200"

  api:
    build: 
      context: .
      dockerfile: Dockerfile
      image: api:1.0
    container_name: api
    ports: 
      - 80:80
    depends_on: 
      - elasticsearch
    
volumes: 
  data:





